#+STARTUP: showall
#+OPTIONS: num:nil
#+TITLE: Linux Manual Pages

* watch(1)
  ~watch [options] command~

  Execute a program periodically, showing output full-screen

  This command is very useful when monitoring some slow change or simply to emulate top.
  I usually run it with ~-d~ flag and ~-n~ set to 1 (one second).

  There are many places this command is useful, I sometimes use it to monitor VCS fail-overs and user activity.

* from(1)
  ~from [-c] [-f file] [-s sender] [user]~

  Print names of those who have sent mail

  This can be used nicely in conjunction with wait to display incoming email.

  ~-s~ option can be used like a filter.

  MAIL environment variable is consulted for the mailbox location, otherwise default of /var/mail/user is used.

* pwdx(1)
  ~pwdx [options] pid [...]~

  Report current working directory of a process

  This is rarely useful, but when it is useful it is /really/ useful.

* paste(1)
  ~paste [OPTION]... [FILE]...~

  Merge lines of files

  This command is very handy when you need to multi-column lists. By default the files are aligned as columns, but if you supply ~-s~ option they will be aligned as rows instead.

  ~-d~ is used when you need something other than TAB separating the columns. Generally the delimiter list will contain /n - 1/ delimiters, where /n/ is the number of columns, which itself will be either number of arguments supplied to ~paste~ or number of lines in the file if ~-s~ was used.

* lscpu(1)
  ~lscpu [-hpx] [-s directory]~

  Display information on CPU architecture

  Quick and easy way to find information about your CPU(s). ~-p~ can be used when this output must be parsed by a script or piped to some other command, it generates a nice CSV list instead of human readable output. If you supply ~-s~ with location of sys filesystem root of another system, it can also give you information about that systems CPU.
